### ISSUE TITLE
Support for multiple sets of API credentials

### ISSUE THREAD

**Issue by edennis** [fremantle-capital/ex_binance#45]
Hey there! 👋🏻 

From what I can gather, it looks as if this repository is largely taken from https://github.com/dvcrn/binance.ex but with a few additions and more maintenance. Currently, the API credentials are configured at a global level for the entire library which makes setting up and getting going for the first time very simple. This approach unfortunately has the drawback that it's not possible to use the library with multiple sets of credentials as is necessary for HFT scenarios with 1000s of bots without running into API rate limiting.

Here's an example of how I solved this for the Kraken client which makes it possible to run the library using both methods: https://github.com/edennis/krakex#usage. I also saw that some of the other client libraries you're maintaining do this in a similar fashion, i.e. https://github.com/fremantle-capital/ex_ftx/blob/main/lib/ex_ftx/credentials.ex

Would you consider a similar change for this library? I'm also happy to help out a little if needed.

Thanks again!

**Comment by rupurt** [comment]
Hey @edennis,

You can pass the credentials along for each call. It's the last parameter e.g. https://github.com/fremantle-capital/ex_binance/blob/main/lib/ex_binance/private.ex#L21

**Comment by edennis** [comment]
@rupurt Ah, fantastic! I seemed to have overlooked that change. Closing.

**Comment by rupurt** [comment]
@edennis no worries.

If you're looking for a higher level API it might be worth checking out my other project https://github.com/fremantle-industries/tai. I'll have to add a venue adapter for kraken using `krakex` :wink:
