### ISSUE TITLE
Augment HTTPClient to include non-signed methods

### ISSUE THREAD

**Issue by edennis** [fremantle-capital/ex_binance#47]
This is not mandatory for this library, but merely a suggestion. I have the following use-case: I've got an application that's already using ex_binance for creating and cancelling orders but I've also got a websocket that subscribes to the user data stream. When trying to [create a listenKey](https://github.com/binance/binance-spot-api-docs/blob/master/user-data-stream.md#create-a-listenkey) I figured I'd just use the `HTTPClient` module since it's already configured to use my credentials. I quickly realized that didn't work as these endpoints only want the api key as a header without the parameter signature. It's easy to work around - I can just send the requests myself using HTTPoison. It would, however, be convenient to only have to configure one http client instead of two. Would you be open to adding the missing http methods to the `HTTPClient` module? (i.e. signed PUT, unsigned DELETE, PUT, POST). I could of course do a PR for that.

**Comment by rupurt** [comment]
@edennis would definitely like this. How do you feel about using pattern matching on the `HTTPClient` module to switch between no auth, auth with credentials and auth with `listenKey`?

**Comment by edennis** [comment]
I'll take a stab at it this week and submit a PR. Thanks for the speedy response!
